In [ ]:
import pandas as pd

In [3]:
transactions_1 = pd.read_csv('transactions_1.csv', index_col=False)
transactions_2 = pd.read_csv('transactions_2.csv', index_col=False)
transactions_3 = pd.read_csv('transactions_3.csv', index_col=False)

In [4]:
transactions_1

,거래일자,거래시각,거래종류,입지내역,적요,Unnamed: 5,통화,거래금액,거래후잔액,단말,거래점,상대계좌
0,2020/08/07,14:10,지급,타행송금,이회숙,NaN,KRW,600000,34143,고대,신한은행,71404250936
1,2020/09/10,23:10,지급,타행송금,이회숙,NaN,KRW,400000,-1316157,고대,신한은행,71404250936 이회숙
2,2021/03/03,10:56,지급,타행송금,봉투 이사 비용,NaN,KRW,1310000,-2115136,고대,신한은행,71404250936 이회숙
3,2021/03/09,11:36,지급,대체,도봉구50기368260회숙,NaN,KRW,32000,-2357566,고대,NaN,232016444137
4,2021/03/24,09:01,지급,타행자동이체,이회숙,NaN,KRW,400300,-2184752,고대,신협,132011849163
5,2021/04/19,11:51,지급,타행송금,이회숙,NaN,KRW,100000,2796808,고대,신한은행,71404250936
6,2021/04/26,09:25,지급,타행자동이체,이회숙,NaN,KRW,400300,4003638,고대,신협,132011849163
7,2021/05/24,09:06,지급,타행자동이체,이회숙,NaN,KRW,400300,2379738,고대,신협,132011849163
8,2021/06/24,09:01,지급,타행자동이체,이회숙,NaN,KRW,400300,116047,고대,신협,132011849163
9,2021/07/26,09:37,지급,타행자동이체,이회숙,NaN,KRW,400300,1910932,고대,신협,132011849163
10,2021/08/24,09:03,지급,타행자동이체,이회숙,NaN,KRW,400300,41829,고대,신협,132011849163
11,2021/09/27,13:34,지급,타행송금,이회숙,NaN,KRW,400000,-4513067,고대,신한은행,71404250936 이회숙
12,2021/10/25,09:25,지급,타행자동이체,이회숙,NaN,KRW,400300,1100920,고대,신협,132011849163
13,2021/11/24,09:00,지급,타행자동이체,이회숙,NaN,KRW,400300,-1273187,고대,신협,132011849163
14,2021/12/24,09:11,지급,타행자동이체,이회숙,NaN,KRW,400300,-1675899,고대,신협,132011849163
15,2022/01/24,09:05,지급,타행자동이체,이회숙,NaN,KRW,400300,-3024332,고대,신협,132011849163
16,2022/02/24,09:02,지급,타행자동이체,이회숙,NaN,KRW,400300,-2669217,고대,신협,132011849163
17,2022/03/24,09:02,지급,타행자동이체,이회숙,NaN,KRW,400300,-4440998,고대,신협,132011849163
18,2022/04/25,09:37,지급,타행자동이체,이회숙,NaN,KRW,400300,-4927646,고대,신협,132011849163
19,2022/05/24,09:02,지급,타행자동이체,이회숙,NaN,KRW,400300,-4672344,고대,신협,132011849163
20,2022/06/24,09:16,지급,타행자동이체,이회숙,NaN,KRW,400300,-4290440,고대,신협,132011849163
21,2022/07/25,09:56,지급,타행자동이체,이회숙,NaN,KRW,400300,-4604818,고대,신협,132011849163
22,2022/08/24,09:02,지급,타행자동이체,이회숙,NaN,KRW,400300,-4725043,고대,신협,132011849163
23,2022/09/26,09:41,지급,타행자동이체,이회숙,NaN,KRW,400300,-4545691,고대,신협,132011849163
24,2022/11/25,22:37,입금,타행이체,이회숙,NaN,KRW,100000,-4890197,조흥은행(신한은행),이회숙,******
25,2023/03/02,19:53,입금,타행이체,NaN,NaN,KRW,200000,-3891825,조흥은행(신한은행),이회숙,******
26,2023/07/02,20:52,지급,타행송금,이회숙,NaN,KRW,360000,-3833650,고대,신한은행,71404250936 이회숙
27,2024/02/25,18:36,지급,타행송금,이회숙,NaN,KRW,150000,-364049,고대,신한은행,71404250936 이회숙
28,2024/03/22,22:15,지급,타행송금,이회숙,NaN,KRW,500000,-873107,고대,신한은행,71404250936 이회숙

In [5]:
df1 = pd.concat([transactions_1, transactions_2])
df2 = transactions_3.copy()
df1['kind'] = 1
df2['kind'] = 2
display(df1.head())
display(df2.head())

,거래일자,거래시각,거래종류,입지내역,적요,Unnamed: 5,통화,거래금액,거래후잔액,단말,거래점,상대계좌,kind
0,2020/08/07,14:10,지급,타행송금,이회숙,NaN,KRW,600000,34143,고대,신한은행,71404250936,1
1,2020/09/10,23:10,지급,타행송금,이회숙,NaN,KRW,400000,-1316157,고대,신한은행,71404250936 이회숙,1
2,2021/03/03,10:56,지급,타행송금,봉투 이사 비용,NaN,KRW,1310000,-2115136,고대,신한은행,71404250936 이회숙,1
3,2021/03/09,11:36,지급,대체,도봉구50기368260회숙,NaN,KRW,32000,-2357566,고대,NaN,232016444137,1
4,2021/03/24,09:01,지급,타행자동이체,이회숙,NaN,KRW,400300,-2184752,고대,신협,132011849163,1

,거래일자,거래시각,거래종류,입지내역,적요,Unnamed: 5,통화,거래금액,거래후잔액,단말,거래점,상대계좌,kind
0,2020/08/07,14:10,지급,타행송금,이회숙,NaN,KRW,600000,34143,고대,신한은행,71404250936 이회숙,2
1,2020/09/10,23:10,지급,타행송금,이회숙,NaN,KRW,400000,-1316157,고대,신한은행,71404250936 이회숙,2
2,2021/03/03,10:56,지급,타행송금,봉투 이사 비용,NaN,KRW,1310000,-2115136,고대,신한은행,71404250936 이회숙,2
3,2021/04/19,11:51,지급,타행송금,이회숙,NaN,KRW,100000,2796808,고대,신한은행,71404250936 이회숙,2
4,2021/09/27,13:34,지급,타행송금,이회숙,NaN,KRW,400000,-4513067,고대,신한은행,71404250936 이회숙,2

In [8]:
df = pd.concat([df1, df2], ignore_index=True)
df.replace({'이회숙':'이희숙', '영마 상환':'엄마 상환'}, inplace=True)
duplicated_mask = df.duplicated(subset=['거래일자', '거래시각'], keep=False)
df.loc[duplicated_mask, 'kind'] = 3
df = df.sort_values(['거래일자', '거래시각']).reset_index(drop=True).drop_duplicates(['거래일자', '거래시각'])
df

,거래일자,거래시각,거래종류,입지내역,적요,Unnamed: 5,통화,거래금액,거래후잔액,단말,거래점,상대계좌,kind
0,2020/08/07,14:10,지급,타행송금,이희숙,NaN,KRW,600000,34143,고대,신한은행,71404250936,3
2,2020/09/10,23:10,지급,타행송금,이희숙,NaN,KRW,400000,-1316157,고대,신한은행,71404250936 이회숙,3
4,2021/03/03,10:56,지급,타행송금,봉투 이사 비용,NaN,KRW,1310000,-2115136,고대,신한은행,71404250936 이회숙,3
6,2021/03/09,11:36,지급,대체,도봉구50기368260회숙,NaN,KRW,32000,-2357566,고대,NaN,232016444137,1
7,2021/03/24,09:01,지급,타행자동이체,이희숙,NaN,KRW,400300,-2184752,고대,신협,132011849163,1
8,2021/04/19,11:51,지급,타행송금,이희숙,NaN,KRW,100000,2796808,고대,신한은행,71404250936,3
10,2021/04/26,09:25,지급,타행자동이체,이희숙,NaN,KRW,400300,4003638,고대,신협,132011849163,1
11,2021/05/24,09:06,지급,타행자동이체,이희숙,NaN,KRW,400300,2379738,고대,신협,132011849163,1
12,2021/06/24,09:01,지급,타행자동이체,이희숙,NaN,KRW,400300,116047,고대,신협,132011849163,1
13,2021/07/26,09:37,지급,타행자동이체,이희숙,NaN,KRW,400300,1910932,고대,신협,132011849163,1
14,2021/08/24,09:03,지급,타행자동이체,이희숙,NaN,KRW,400300,41829,고대,신협,132011849163,1
15,2021/09/27,13:34,지급,타행송금,이희숙,NaN,KRW,400000,-4513067,고대,신한은행,71404250936 이회숙,3
17,2021/10/25,09:25,지급,타행자동이체,이희숙,NaN,KRW,400300,1100920,고대,신협,132011849163,1
18,2021/11/24,09:00,지급,타행자동이체,이희숙,NaN,KRW,400300,-1273187,고대,신협,132011849163,1
19,2021/12/24,09:11,지급,타행자동이체,이희숙,NaN,KRW,400300,-1675899,고대,신협,132011849163,1
20,2022/01/24,09:05,지급,타행자동이체,이희숙,NaN,KRW,400300,-3024332,고대,신협,132011849163,1
21,2022/02/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400300,-2669217,고대,신협,132011849163,1
22,2022/03/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400300,-4440998,고대,신협,132011849163,1
23,2022/04/25,09:37,지급,타행자동이체,이희숙,NaN,KRW,400300,-4927646,고대,신협,132011849163,1
24,2022/05/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400300,-4672344,고대,신협,132011849163,1
25,2022/06/24,09:16,지급,타행자동이체,이희숙,NaN,KRW,400300,-4290440,고대,신협,132011849163,1
26,2022/07/25,09:56,지급,타행자동이체,이희숙,NaN,KRW,400300,-4604818,고대,신협,132011849163,1
27,2022/08/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400300,-4725043,고대,신협,132011849163,1
28,2022/09/26,09:41,지급,타행자동이체,이희숙,NaN,KRW,400300,-4545691,고대,신협,132011849163,1
29,2022/11/25,22:37,입금,타행이체,이희숙,NaN,KRW,100000,-4890197,조흥은행(신한은행),이희숙,******,1
30,2023/03/02,19:53,입금,타행이체,NaN,NaN,KRW,200000,-3891825,조흥은행(신한은행),이희숙,******,1
31,2023/07/02,20:52,지급,타행송금,이희숙,NaN,KRW,360000,-3833650,고대,신한은행,71404250936 이회숙,3
33,2024/02/25,18:36,지급,타행송금,이희숙,NaN,KRW,150000,-364049,고대,신한은행,71404250936 이회숙,3
35,2024/03/06,09:02,지급,타행자동이체,엄마 상환,NaN,KRW,500300,23206,고대,신한은행,71404250936 이회숙,2
36,2024/03/22,22:15,지급,타행송금,이희숙,NaN,KRW,500000,-873107,고대,신한은행,71404250936 이회숙,3
38,2024/04/08,09:03,지급,타행자동이체,엄마 상환,NaN,KRW,500300,-1587883,고대,신한은행,71404250936 이회숙,2
39,2024/05/07,09:08,지급,타행자동이체,엄마 상환,NaN,KRW,500300,-613698,고대,신한은행,71404250936 이회숙,2
40,2024/05/08,12:59,지급,타행송금,이희숙,NaN,KRW,300000,-913698,고대,신한은행,71404250936 이회숙,3
42,2024/06/07,09:04,지급,타행자동이체,엄마 상환,NaN,KRW,500300,-218672,고대,신한은행,71404250936 이회숙,2
43,2024/07/08,09:04,지급,타행자동이체,엄마 상환,NaN,KRW,500300,-1529012,고대,신한은행,71404250936 이회숙,2
44,2024/08/06,09:02,지급,타행자동이체,엄마 상환,NaN,KRW,500300,-3816769,고대,신한은행,71404250936 이회숙,2
45,2024/10/22,14:55,지급,타행송금,이희숙,NaN,KRW,2200000,-763675,고대,신한은행,71404250936 이회숙,3
47,2025/02/18,08:09,지급,타행송금,이희숙,NaN,KRW,50000,315363,고대,신한은행,71404250936 이회숙,3
49,2025/09/03,11:39,지급,타행송금,엄마 상환,NaN,KRW,500000,1478220,고대,신한은행,71404250936 이회숙,3
51,2025/10/05,11:53,지급,타행송금,엄마 상환,NaN,KRW,500000,660440,고대,신한은행,71404250936 이회숙,3
53,2025/11/04,11:55,지급,타행송금,엄마 상환,NaN,KRW,500000,385402,고대,신한은행,71404250936 이회숙,3
55,2025/12/01,09:42,지급,타행자동이체,엄마 상환,NaN,KRW,500300,126522,고대,신한은행,71404250936 이회숙,2
56,2026/01/02,09:20,지급,타행자동이체,엄마 상환,NaN,KRW,500300,436137,고대,신한은행,71404250936 이회숙,2
57,2026/02/02,09:27,지급,타행자동이체,엄마 상환,NaN,KRW,500300,304665,고대,신한은행,71404250936 이회숙,2
58,2026/03/03,09:30,지급,타행자동이체,엄마 상환,NaN,KRW,500300,77069,고대,신한은행,71404250936 이회숙,2

In [9]:
df['거래금액'].value_counts()

거래금액
400300     18
500300     10
500000      4
400000      2
100000      2
600000      1
1310000     1
32000       1
200000      1
360000      1
150000      1
300000      1
2200000     1
50000       1
Name: count, dtype: int64

In [ ]:
# df = df[df['거래금액'].isin([500000,500300,400000,400300])]
# df.replace({400300:400000,500300:500000},inplace=True)
# df

,거래일자,거래시각,거래종류,입지내역,적요,Unnamed: 5,통화,거래금액,거래후잔액,단말,거래점,상대계좌,kind
2,2020/09/10,23:10,지급,타행송금,이희숙,NaN,KRW,400000,-1316157,고대,신한은행,71404250936 이회숙,3
7,2021/03/24,09:01,지급,타행자동이체,이희숙,NaN,KRW,400000,-2184752,고대,신협,132011849163,1
10,2021/04/26,09:25,지급,타행자동이체,이희숙,NaN,KRW,400000,4003638,고대,신협,132011849163,1
11,2021/05/24,09:06,지급,타행자동이체,이희숙,NaN,KRW,400000,2379738,고대,신협,132011849163,1
12,2021/06/24,09:01,지급,타행자동이체,이희숙,NaN,KRW,400000,116047,고대,신협,132011849163,1
13,2021/07/26,09:37,지급,타행자동이체,이희숙,NaN,KRW,400000,1910932,고대,신협,132011849163,1
14,2021/08/24,09:03,지급,타행자동이체,이희숙,NaN,KRW,400000,41829,고대,신협,132011849163,1
15,2021/09/27,13:34,지급,타행송금,이희숙,NaN,KRW,400000,-4513067,고대,신한은행,71404250936 이회숙,3
17,2021/10/25,09:25,지급,타행자동이체,이희숙,NaN,KRW,400000,1100920,고대,신협,132011849163,1
18,2021/11/24,09:00,지급,타행자동이체,이희숙,NaN,KRW,400000,-1273187,고대,신협,132011849163,1
19,2021/12/24,09:11,지급,타행자동이체,이희숙,NaN,KRW,400000,-1675899,고대,신협,132011849163,1
20,2022/01/24,09:05,지급,타행자동이체,이희숙,NaN,KRW,400000,-3024332,고대,신협,132011849163,1
21,2022/02/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400000,-2669217,고대,신협,132011849163,1
22,2022/03/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400000,-4440998,고대,신협,132011849163,1
23,2022/04/25,09:37,지급,타행자동이체,이희숙,NaN,KRW,400000,-4927646,고대,신협,132011849163,1
24,2022/05/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400000,-4672344,고대,신협,132011849163,1
25,2022/06/24,09:16,지급,타행자동이체,이희숙,NaN,KRW,400000,-4290440,고대,신협,132011849163,1
26,2022/07/25,09:56,지급,타행자동이체,이희숙,NaN,KRW,400000,-4604818,고대,신협,132011849163,1
27,2022/08/24,09:02,지급,타행자동이체,이희숙,NaN,KRW,400000,-4725043,고대,신협,132011849163,1
28,2022/09/26,09:41,지급,타행자동이체,이희숙,NaN,KRW,400000,-4545691,고대,신협,132011849163,1
35,2024/03/06,09:02,지급,타행자동이체,엄마 상환,NaN,KRW,500000,23206,고대,신한은행,71404250936 이회숙,2
36,2024/03/22,22:15,지급,타행송금,이희숙,NaN,KRW,500000,-873107,고대,신한은행,71404250936 이회숙,3
38,2024/04/08,09:03,지급,타행자동이체,엄마 상환,NaN,KRW,500000,-1587883,고대,신한은행,71404250936 이회숙,2
39,2024/05/07,09:08,지급,타행자동이체,엄마 상환,NaN,KRW,500000,-613698,고대,신한은행,71404250936 이회숙,2
42,2024/06/07,09:04,지급,타행자동이체,엄마 상환,NaN,KRW,500000,-218672,고대,신한은행,71404250936 이회숙,2
43,2024/07/08,09:04,지급,타행자동이체,엄마 상환,NaN,KRW,500000,-1529012,고대,신한은행,71404250936 이회숙,2
44,2024/08/06,09:02,지급,타행자동이체,엄마 상환,NaN,KRW,500000,-3816769,고대,신한은행,71404250936 이회숙,2
49,2025/09/03,11:39,지급,타행송금,엄마 상환,NaN,KRW,500000,1478220,고대,신한은행,71404250936 이회숙,3
51,2025/10/05,11:53,지급,타행송금,엄마 상환,NaN,KRW,500000,660440,고대,신한은행,71404250936 이회숙,3
53,2025/11/04,11:55,지급,타행송금,엄마 상환,NaN,KRW,500000,385402,고대,신한은행,71404250936 이회숙,3
55,2025/12/01,09:42,지급,타행자동이체,엄마 상환,NaN,KRW,500000,126522,고대,신한은행,71404250936 이회숙,2
56,2026/01/02,09:20,지급,타행자동이체,엄마 상환,NaN,KRW,500000,436137,고대,신한은행,71404250936 이회숙,2
57,2026/02/02,09:27,지급,타행자동이체,엄마 상환,NaN,KRW,500000,304665,고대,신한은행,71404250936 이회숙,2
58,2026/03/03,09:30,지급,타행자동이체,엄마 상환,NaN,KRW,500000,77069,고대,신한은행,71404250936 이회숙,2

In [14]:
print(df['거래금액'].value_counts())
print(df['거래금액'].count())
print(df['거래금액'].sum())

거래금액
400000    20
500000    14
Name: count, dtype: int64
34
15000000

In [20]:
df = df[['거래일자', '거래시각', '거래종류', '입지내역', '적요', '통화', '거래금액', '단말','거래점','상대계좌']]
df.to_csv('transfer_history.csv',index=False, encoding='utf-8-sig')