In [1]:
import pandas as pd

In [2]:
# sec 01
menu = pd.Series(['비빔밥', '김치찌개','된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [3]:
price = pd.Series(['10000', '9000','8000'])
price

0    10000
1     9000
2     8000
dtype: object

In [4]:
pd.DataFrame({
    "메뉴":menu,
    "가격":price
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [5]:
df = pd.DataFrame({
    "메뉴":['비빔밥', '김치찌개','된장찌개'],
    "가격":['10000', '9000','8000'],
    "원산지":['국내산']*3
})

In [6]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [7]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [8]:
df[['메뉴', '가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [9]:
print(type(df))
print(type(df['가격']))
print(type(df[['가격']]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [10]:
# sec 02

df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500,5000,5500,5000,4000,5900,5300],
    "칼로리":[10,110,250,110,20,210,0]
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [11]:
df.to_csv('temp.csv')

In [12]:
temp_df = pd.read_csv('temp.csv')
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [13]:
df.to_csv('cafe.csv', index=False)
df = pd.read_csv('temp.csv')
df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [14]:
# sec 03
df.head(2)

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110

In [15]:
df.tail(3)

   Unnamed: 0     메뉴    가격  칼로리
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [16]:
df.sample(3)

   Unnamed: 0     메뉴    가격  칼로리
4           4  에스프레소  4000   20
2           2   카페모카  5500  250
6           6     녹차  5300    0

In [17]:
df.shape

(7, 4)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7 non-null      int64
 1   메뉴          7 non-null      object
 2   가격          7 non-null      int64
 3   칼로리         7 non-null      int64
dtypes: int64(3), object(1)
memory usage: 356.0+ bytes

In [19]:
df.corr(numeric_only=True)

            Unnamed: 0        가격       칼로리
Unnamed: 0    1.000000  0.329759 -0.046569
가격            0.329759  1.000000  0.713227
칼로리          -0.046569  0.713227  1.000000

In [20]:
df_car = pd.DataFrame({
    "car":['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    "size":["S",'M','S','S','M','M','L','S','S','M','S']
})
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [21]:
df_car.nunique()

car     2
size    3
dtype: int64

In [22]:
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [23]:
print(df_car['car'].value_counts())
print(df_car['size'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [24]:
df.describe()

       Unnamed: 0           가격         칼로리
count    7.000000     7.000000    7.000000
mean     3.000000  5028.571429  101.428571
std      2.160247   631.702160   99.402980
min      0.000000  4000.000000    0.000000
25%      1.500000  4750.000000   15.000000
50%      3.000000  5000.000000  110.000000
75%      4.500000  5400.000000  160.000000
max      6.000000  5900.000000  250.000000

In [25]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [26]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [27]:
# sec 04
data = df.copy()
data['가격'] = data['가격'].astype('float')
data

   Unnamed: 0     메뉴      가격  칼로리
0           0  아메리카노  4500.0   10
1           1   카페라떼  5000.0  110
2           2   카페모카  5500.0  250
3           3   카푸치노  5000.0  110
4           4  에스프레소  4000.0   20
5           5    밀크티  5900.0  210
6           6     녹차  5300.0    0

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7 non-null      int64
 1   메뉴          7 non-null      object
 2   가격          7 non-null      float64
 3   칼로리         7 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 356.0+ bytes

In [29]:
df['가격'] = df['가격'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7 non-null      int64
 1   메뉴          7 non-null      object
 2   가격          7 non-null      int32
 3   칼로리         7 non-null      int64
dtypes: int32(1), int64(2), object(1)
memory usage: 328.0+ bytes

In [30]:
df['칼로리'] = df['칼로리'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7 non-null      int64
 1   메뉴          7 non-null      object
 2   가격          7 non-null      int32
 3   칼로리         7 non-null      float64
dtypes: float64(1), int32(1), int64(1), object(1)
memory usage: 328.0+ bytes

In [31]:
# sec 05
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [32]:
df['new'] = 0
df.head(2)

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0

In [33]:
discount = 0.2
df['할인가'] = df['가격'] * (1-discount)
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [34]:
# 06 데이터 삭제
df = pd.read_csv('cafe.csv')
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [35]:
df.drop(1,axis=0, inplace=True)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [36]:
df = df.drop('칼로리', axis=1)
df

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000
4  에스프레소  4000
5    밀크티  5900
6     녹차  5300

In [37]:
df = pd.read_csv('cafe.csv')
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [38]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [39]:
df.loc[0,'가격']

4500

In [40]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [41]:
df.loc[2, '메뉴': '칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [42]:
df.loc[2, ['메뉴', '칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [43]:
df.loc[1:, '메뉴': '가격']

      메뉴    가격
1   카페라떼  5000
2   카페모카  5500
3   카푸치노  5000
4  에스프레소  4000
5    밀크티  5900
6     녹차  5300

In [44]:
df = pd.read_csv('cafe.csv')
df.drop(0, inplace=True)
df

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [45]:
df.iloc[1]

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [46]:
df.loc[1]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [47]:
df.iloc[:,1]

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [48]:
df.iloc[2,0:2]

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [49]:
df

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [50]:
display(df.loc[2,'메뉴':'칼로리'])
display(df.iloc[2,0:2])

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [51]:
# sec 09
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [52]:
import numpy as np
df['원산지'] = np.nan
df

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN
4  에스프레소  4000   20  NaN
5    밀크티  5900  210  NaN
6     녹차  5300    0  NaN

In [53]:
df.loc[0, '원산지'] = '콜롬비아'
df.loc[2:3,'원산지'] = '과테말라'
df

C:\Users\sjkim\AppData\Local\Temp\ipykernel_27852\137614153.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, '원산지'] = '콜롬비아'

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN

In [54]:
df.loc['시즌'] = ['크리스마스라떼', 6000,300, '한국']
df

         메뉴    가격  칼로리   원산지
0     아메리카노  4500   10  콜롬비아
1      카페라떼  5000  110   NaN
2      카페모카  5500  250  과테말라
3      카푸치노  5000  110  과테말라
4     에스프레소  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
시즌  크리스마스라떼  6000  300    한국

In [55]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [56]:
df.loc[7] = {'메뉴':'딴짓커피', '가격':2000, '칼로리':20}
df

         메뉴    가격  칼로리   원산지
0     아메리카노  4500   10  콜롬비아
1      카페라떼  5000  110   NaN
2      카페모카  5500  250  과테말라
3      카푸치노  5000  110  과테말라
4     에스프레소  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
시즌  크리스마스라떼  6000  300    한국
7      딴짓커피  2000   20   NaN

In [57]:
df.drop("시즌", inplace=True)
df.to_csv("cafe2.csv",index=False)
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [58]:
# sec 10
df = pd.read_csv('cafe2.csv')
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [59]:
df.sort_index(ascending=False)

      메뉴    가격  칼로리   원산지
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN
5    밀크티  5900  210   NaN
4  에스프레소  4000   20   NaN
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
0  아메리카노  4500   10  콜롬비아

In [60]:
df.sort_values('메뉴', ascending=True)

      메뉴    가격  칼로리   원산지
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN
5    밀크티  5900  210   NaN
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라

In [61]:
df.sort_values(['가격','메뉴'], ascending=[False,True], inplace=True)
df

      메뉴    가격  칼로리   원산지
5    밀크티  5900  210   NaN
2   카페모카  5500  250  과테말라
6     녹차  5300    0   NaN
1   카페라떼  5000  110   NaN
3   카푸치노  5000  110  과테말라
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [62]:
df.reset_index(drop=True)

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [63]:
# sec 11
df = pd.read_csv('cafe2.csv')
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [64]:
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [65]:
cond = df['칼로리'] < 50
df[cond]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [66]:
cond = df['칼로리'] < 50
df[~cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [67]:
cond1 = df['가격'] >= 5000
cond2 = df['칼로리'] > 100
df[cond1&cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [68]:
cond1 = df['가격'] >= 5000
cond2 = df['칼로리'] > 100
df[cond1|cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN
6    녹차  5300    0   NaN

In [69]:
df[df['원산지']=='과테말라']

     메뉴    가격  칼로리   원산지
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라

In [70]:
df[(df['원산지']=='과테말라')&(df['가격']<=5000)]

     메뉴    가격  칼로리   원산지
3  카푸치노  5000  110  과테말라

In [71]:
df[df.메뉴.isin(['녹차'])]

   메뉴    가격  칼로리  원산지
6  녹차  5300    0  NaN

In [72]:
df[df.메뉴.isin(['녹차', '카푸치노', '카페라떼'])]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
3  카푸치노  5000  110  과테말라
6    녹차  5300    0   NaN

In [73]:
# sec 12 : 결측치 처리
df = pd.read_csv('cafe2.csv')
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [74]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [75]:
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [76]:
df.isna()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [77]:
df['원산지'].fillna('코스타리카',inplace=True)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [78]:
df.to_csv('cafe3.csv',index=False)

In [79]:
# sec 13 값 변경
df = pd.read_csv("cafe3.csv")
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [80]:
df.replace('아메리카노','룽고', inplace=True)
df.replace('녹차','그린티', inplace=True)
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [81]:
change = {'룽고':'아메리카노','그린티':'녹차'}
df = df.replace(change)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [82]:
df.loc[6, '원산지'] = '대한민국'
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0   대한민국
7   딴짓커피  2000   20  코스타리카

In [83]:
df.loc[1:2, '이벤트가'] = 1000
df.to_csv('cafe4.csv', index=False)

In [84]:
df = pd.DataFrame({'만족도':['만족','보통','불만','보통','만족']})
mapping = {'만족':3,'보통':2,'불만':1}
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3

In [85]:
# sec 14 : 문자열
df = pd.DataFrame({'A':['데이터 분석', '기본 학습서', '퇴근 후 열공'],
                   'B':[10,20,30],
                   'C':['ab cd', 'AB CD', 'ab cd']})
df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [86]:
df['A'] = df['A'].replace('분석','시각화')
df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [87]:
df['A'] = df['A'].str.replace('분석','시각화')
df

         A   B      C
0  데이터 시각화  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [88]:
df['B'] = df['B'].replace(10, 100)
df

         A    B      C
0  데이터 시각화  100  ab cd
1   기본 학습서   20  AB CD
2  퇴근 후 열공   30  ab cd

In [89]:
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [90]:
df['A'].str.split()[0]

['데이터', '시각화']

In [91]:
df['D'] = df['A'].str.split().str[0]
df

         A    B      C    D
0  데이터 시각화  100  ab cd  데이터
1   기본 학습서   20  AB CD   기본
2  퇴근 후 열공   30  ab cd   퇴근

In [92]:
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [93]:
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B      C    D  기본포함유무
0  데이터 시각화  100  ab cd  데이터   False
1   기본 학습서   20  AB CD   기본    True
2  퇴근 후 열공   30  ab cd   퇴근   False

In [94]:
df['문자길이'] = df['A'].str.len()
df

         A    B      C    D  기본포함유무  문자길이
0  데이터 시각화  100  ab cd  데이터   False     7
1   기본 학습서   20  AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd   퇴근   False     7

In [95]:
display(df['C'].str.lower())
display(df['C'].str.upper())
display(df['C'].str.replace(" ",""))
df['C'] = df['C'].str.replace(" ","")
df

0    ab cd
1    ab cd
2    ab cd
Name: C, dtype: object

0    AB CD
1    AB CD
2    AB CD
Name: C, dtype: object

0    abcd
1    ABCD
2    abcd
Name: C, dtype: object

         A    B     C    D  기본포함유무  문자길이
0  데이터 시각화  100  abcd  데이터   False     7
1   기본 학습서   20  ABCD   기본    True     6
2  퇴근 후 열공   30  abcd   퇴근   False     7

In [96]:
df['C'].str[1:3]

0    bc
1    BC
2    bc
Name: C, dtype: object

In [97]:
# sec 15 : 내장함수
df = pd.read_csv('cafe4.csv')
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓커피  2000   20  코스타리카     NaN

In [98]:
len(df)

8

In [99]:
cond = df['가격']>5000
sum(cond)

3

In [100]:
df.sum(numeric_only=True)

가격      37200.0
칼로리       730.0
이벤트가     2000.0
dtype: float64

In [101]:
df.T

          0       1       2     3      4      5     6      7
메뉴    아메리카노    카페라떼    카페모카  카푸치노  에스프레소    밀크티    녹차   딴짓커피
가격     4500    5000    5500  5000   4000   5900  5300   2000
칼로리      10     110     250   110     20    210     0     20
원산지    콜롬비아   코스타리카    과테말라  과테말라  코스타리카  코스타리카  대한민국  코스타리카
이벤트가    NaN  1000.0  1000.0   NaN    NaN    NaN   NaN    NaN

In [102]:
df.sum(axis=1, numeric_only=True)

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    2020.0
dtype: float64

In [103]:
print(df['가격'].max())
print(df['가격'].min())
print(df['가격'].mean())
print(df['가격'].median())
print(df['가격'].sum())
print(df['가격'].std())
print(df['가격'].var())
print(df['가격'].quantile(.25))
print(df['가격'].quantile(.75))

5900
2000
4650.0
5000.0
37200
1220.070255588353
1488571.4285714286
4375.0
5350.0

In [104]:
df[df['가격']<df['가격'].quantile(.25)]

      메뉴    가격  칼로리    원산지  이벤트가
4  에스프레소  4000   20  코스타리카   NaN
7   딴짓커피  2000   20  코스타리카   NaN

In [105]:
df['원산지'].mode()

0    코스타리카
Name: 원산지, dtype: object

In [106]:
df['가격'].idxmax()

5

In [107]:
max_ind = df['가격'].idxmax()
df.loc[max_ind]

메뉴        밀크티
가격       5900
칼로리       210
원산지     코스타리카
이벤트가      NaN
Name: 5, dtype: object

In [108]:
df.loc[max_ind]['메뉴']

'밀크티'

In [109]:
df.nlargest(3, '가격')

     메뉴    가격  칼로리    원산지    이벤트가
5   밀크티  5900  210  코스타리카     NaN
2  카페모카  5500  250   과테말라  1000.0
6    녹차  5300    0   대한민국     NaN

In [110]:
df.nsmallest(2, '가격')

      메뉴    가격  칼로리    원산지  이벤트가
7   딴짓커피  2000   20  코스타리카   NaN
4  에스프레소  4000   20  코스타리카   NaN

In [111]:
def cal(x):
    if x>=100:
        return "No"
    else:
        return "Yes"
df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

      메뉴    가격  칼로리    원산지    이벤트가 먹어도 될까요
0  아메리카노  4500   10   콜롬비아     NaN     Yes
1   카페라떼  5000  110  코스타리카  1000.0      No
2   카페모카  5500  250   과테말라  1000.0      No
3   카푸치노  5000  110   과테말라     NaN      No
4  에스프레소  4000   20  코스타리카     NaN     Yes
5    밀크티  5900  210  코스타리카     NaN      No
6     녹차  5300    0   대한민국     NaN     Yes
7   딴짓커피  2000   20  코스타리카     NaN     Yes

In [112]:
df = pd.DataFrame({'Name':{0:'쿼카',1:'알파카',2:'시바견'},
                   '수학':{0:90, 1:93, 2:85},
                   '영어':{0:92, 1:84, 2:86},
                   '국어':{0:91, 1:94, 2:83}
                   })
df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [113]:
pd.melt(df, id_vars=['Name'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [114]:
pd.melt(df, id_vars=['Name'], value_vars=['수학','영어'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86

In [115]:
pd.melt(df, id_vars=['Name'], var_name='과목', value_name='점수')

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86
6   쿼카  국어  91
7  알파카  국어  94
8  시바견  국어  83

In [116]:
df = df.rename(columns={'Name':'이름'})
df['반'] = ['A반'] * 2 + ['B반']
df = df[['반', '이름', '수학', '영어', '국어']]
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  86  83

In [117]:
# sec 16 그룹핑
df = pd.read_csv('cafe4.csv')
df.groupby(['원산지']).mean(numeric_only=True)

           가격    칼로리    이벤트가
원산지
과테말라   5250.0  180.0  1000.0
대한민국   5300.0    0.0     NaN
코스타리카  4225.0   90.0  1000.0
콜롬비아   4500.0   10.0     NaN

In [118]:
df.groupby(['원산지', '칼로리']).mean(numeric_only=True)

               가격    이벤트가
원산지   칼로리
과테말라  110  5000.0     NaN
      250  5500.0  1000.0
대한민국  0    5300.0     NaN
코스타리카 20   3000.0     NaN
      110  5000.0  1000.0
      210  5900.0     NaN
콜롬비아  10   4500.0     NaN

In [119]:
df.groupby(['원산지', '메뉴']).agg(['mean', 'sum'])

                 가격          칼로리         이벤트가
               mean   sum   mean  sum    mean     sum
원산지   메뉴
과테말라  카페모카   5500.0  5500  250.0  250  1000.0  1000.0
      카푸치노   5000.0  5000  110.0  110     NaN     0.0
대한민국  녹차     5300.0  5300    0.0    0     NaN     0.0
코스타리카 딴짓커피   2000.0  2000   20.0   20     NaN     0.0
      밀크티    5900.0  5900  210.0  210     NaN     0.0
      에스프레소  4000.0  4000   20.0   20     NaN     0.0
      카페라떼   5000.0  5000  110.0  110  1000.0  1000.0
콜롬비아  아메리카노  4500.0  4500   10.0   10     NaN     0.0

In [120]:
df.groupby(['원산지', '칼로리']).mean(numeric_only=True).reset_index()

     원산지  칼로리      가격    이벤트가
0   과테말라  110  5000.0     NaN
1   과테말라  250  5500.0  1000.0
2   대한민국    0  5300.0     NaN
3  코스타리카   20  3000.0     NaN
4  코스타리카  110  5000.0  1000.0
5  코스타리카  210  5900.0     NaN
6   콜롬비아   10  4500.0     NaN

In [121]:
df = pd.DataFrame({
    '과일':['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '가격':[1000, None, 1500, None, 2000, 2500, None, 1800]
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [122]:
price = df.groupby('과일')['가격'].transform('mean')
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [123]:
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [124]:
df = pd.DataFrame({
    '과일':['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '등급':['B']*2+['A']*4+['B']*2,
    '가격':[1000, None, 1500, None, 2000, 2500, None, 1800]
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [125]:
price = df.groupby(['과일', '등급'])['가격'].transform('mean')
df['가격'] = df['가격'].fillna(price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [126]:
# unstack 생략

In [ ]:
# sec 17 : 시계열 데이터
data = {
    'Date1' : ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
    'Date2' : ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
    'Date3' : ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
    'Date4' : ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
    'Date5' : ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
    'DateTime1' : ['24-02-17 13:50:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
    'DateTime2' : ['2024-02-17 13:50:30', '2024-02-18 14:55:45', '2024-02-19 15:30:15', '2024-02-20 16:10:50'],
    'DateTime3' : ['02/17/2024 01:50:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
    'DateTime4' : ['17 Feb 2024 13:50:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50'],
}

df = pd.DataFrame(data)
df.to_csv('date_data.csv', index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:50:30,2024-02-17 13:50:30,02/17/2024 01:50:30 PM,17 Feb 2024 13:50:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14:55:45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15:30:15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16:10:50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [129]:
df = pd.read_csv('date_data.csv')
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'])
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H:%M:%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      datetime64[ns]
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      datetime64[ns]
 4   Date5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      datetime64[ns]
 8   DateTime4  4 non-null      object
dtypes: datetime64[ns](8), object(1)
memory usage: 420.0+ bytes

C:\Users\sjkim\AppData\Local\Temp\ipykernel_27852\3814821835.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])
C:\Users\sjkim\AppData\Local\Temp\ipykernel_27852\3814821835.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime1'] = pd.to_datetime(df['DateTime1'])
C:\Users\sjkim\AppData\Local\Temp\ipykernel_27852\3814821835.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime3'] = pd.to_datetime(df['DateTime3'])

In [130]:
df['year']   = df['DateTime1'].dt.year
df['month']  = df['DateTime1'].dt.month
df['day']    = df['DateTime1'].dt.day
df['hour']   = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second
df['dow']    = df['DateTime1'].dt.dayofweek
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,second,dow
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2017-02-24 13:50:30,2024-02-17 13:50:30,2024-02-17 13:50:30,17 Feb 2024 13:50:30,2017,2,24,13,50,30,4
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2018-02-24 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,18 Feb 2024 14:55:45,2018,2,24,14,55,45,5
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2019-02-24 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,19 Feb 2024 15:30:15,2019,2,24,15,30,15,6
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2020-02-24 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,20 Feb 2024 16:10:50,2020,2,24,16,10,50,0

In [131]:
display(df['DateTime1'].dt.to_period('Y'))
display(df['DateTime1'].dt.to_period('Q'))
display(df['DateTime1'].dt.to_period('M'))
display(df['DateTime1'].dt.to_period('D'))
display(df['DateTime1'].dt.to_period('H'))

0    2017
1    2018
2    2019
3    2020
Name: DateTime1, dtype: period[A-DEC]

0    2017Q1
1    2018Q1
2    2019Q1
3    2020Q1
Name: DateTime1, dtype: period[Q-DEC]

0    2017-02
1    2018-02
2    2019-02
3    2020-02
Name: DateTime1, dtype: period[M]

0    2017-02-24
1    2018-02-24
2    2019-02-24
3    2020-02-24
Name: DateTime1, dtype: period[D]

0    2017-02-24 13:00
1    2018-02-24 14:00
2    2019-02-24 15:00
3    2020-02-24 16:00
Name: DateTime1, dtype: period[H]

In [142]:
# sec 18 : 시계열 데이터 (timedelta)
df = pd.read_csv('date_data.csv', usecols=['DateTime4'], parse_dates=['DateTime4'])
df

            DateTime4
0 2024-02-17 13:50:30
1 2024-02-18 14:55:45
2 2024-02-19 15:30:15
3 2024-02-20 16:10:50

In [144]:
day = pd.Timedelta(days=99)
df['100day'] = df['DateTime4'] + day
df

            DateTime4              100day
0 2024-02-17 13:50:30 2024-05-26 13:50:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50

In [145]:
hour = pd.Timedelta(hours=100)
df['100hour'] = df['DateTime4'] + hour
df

            DateTime4              100day             100hour
0 2024-02-17 13:50:30 2024-05-26 13:50:30 2024-02-21 17:50:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45 2024-02-22 18:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15 2024-02-23 19:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50 2024-02-24 20:10:50

In [146]:
difference = pd.Timedelta(weeks=7, days=7, hours=7, minutes=7, seconds=7)
df['difference'] = df['DateTime4'] - difference
df

,DateTime4,100day,100hour,difference
0,2024-02-17 13:50:30,2024-05-26 13:50:30,2024-02-21 17:50:30,2023-12-23 06:43:23
1,2024-02-18 14:55:45,2024-05-27 14:55:45,2024-02-22 18:55:45,2023-12-24 07:48:38
2,2024-02-19 15:30:15,2024-05-28 15:30:15,2024-02-23 19:30:15,2023-12-25 08:23:08
3,2024-02-20 16:10:50,2024-05-29 16:10:50,2024-02-24 20:10:50,2023-12-26 09:03:43

In [147]:
diff = df['100hour'] - df['difference']
diff

0   60 days 11:07:07
1   60 days 11:07:07
2   60 days 11:07:07
3   60 days 11:07:07
dtype: timedelta64[ns]

In [151]:
print(diff.dt.total_seconds())
print(diff.dt.total_seconds()/60)
print(diff.dt.total_seconds()/60/60)
print(diff.dt.total_seconds()/60/60/24)

0    5224027.0
1    5224027.0
2    5224027.0
3    5224027.0
dtype: float64
0    87067.116667
1    87067.116667
2    87067.116667
3    87067.116667
dtype: float64
0    1451.118611
1    1451.118611
2    1451.118611
3    1451.118611
dtype: float64
0    60.463275
1    60.463275
2    60.463275
3    60.463275
dtype: float64

In [ ]:
print(diff.dt.days)
print(diff.dt.days)