In [1]:
import pandas as pd

In [ ]:
# sec 01
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [11]:
df = df[df['f5']!=0]
df['views'] = df['views'].fillna(df['views'].min())
display(df)
print(f'views 중앙값 : {int(df['views'].median())}')

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

views 중앙값 : 5924

In [21]:
# sec 02
df = pd.read_csv('type1_data1.csv')
# display(df)
freq_date = df['subscribed'].mode()[0]
print(f"가장 빈도수가 많은 날짜 : {freq_date}")
# df['subscribed'] = df['subscribed'].astype(datetime)
print(f"가장 빈도수가 많은 날짜의 일(day) : {int(freq_date[-2:])}")

가장 빈도수가 많은 날짜 : 2025-02-17
가장 빈도수가 많은 날짜의 일(day) : 17

In [ ]:
freq_date = df['subscribed'].value_counts().index[0]
freq_date

'2025-02-17'

In [64]:
df = pd.read_csv('type1_data1.csv')
df['subscribed'] = pd.to_datetime(df['subscribed'])
freq_date = df['subscribed'].mode()[0]
freq_date.day

17

In [40]:
# sec 03
df = pd.read_csv('type1_data1.csv')
df = df.dropna()
df['views/f1'] = df['views'] / df['f1']
df[df['views/f1']==df['views/f1'].max()]['age'].values[0]

22.0

In [45]:
df = pd.read_csv('type1_data1.csv')
df = df.dropna()
df['views/f1'] = df['views'] / df['f1']
df.sort_values('views/f1', ascending=False).iloc[0]['age']

22.0

In [66]:
# sec 04
df = pd.read_csv('type1_data1.csv')
df['views'] = df['views'].fillna(0)
df = df.sort_values(by='views', ascending=False)
views10 = df.iloc[9]['views']
df['views'] = [views10]*10+list(df['views'])[10:]
print(f"views 컬럼의 전체 합 : {int(df['views'].sum())}")
df

views 컬럼의 전체 합 : 652812

        id   age city    f1  f2   f3    f4         f5  subscribed   views
5     id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56    id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83    id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32    id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
100  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
..     ...   ...  ...   ...  ..  ...   ...        ...         ...     ...
93    id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07    42.0
20    id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16     0.0
48    id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25     0.0
39    id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22     0.0
82    id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17     0.0

[120 rows x 10 columns]

In [67]:
df = pd.read_csv('type1_data1.csv')
df['views'] = df['views'].fillna(0)
df = df.sort_values(by='views', ascending=False)
views_min = df.iloc[:10]['views'].min()
df.iloc[:10,-1] = views_min
df

        id   age city    f1  f2   f3    f4         f5  subscribed   views
5     id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56    id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83    id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32    id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
100  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
..     ...   ...  ...   ...  ..  ...   ...        ...         ...     ...
93    id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07    42.0
20    id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16     0.0
48    id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25     0.0
39    id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22     0.0
82    id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17     0.0

[120 rows x 10 columns]

In [72]:
# sec 05
df = pd.read_csv('type1_data1.csv')
df_fj = df[df['f4'].str.endswith('FJ')]
print(f" f2컬럼의 평균값 : {round(df_fj['f2'].mean(),2)}")

 f2컬럼의 평균값 : 0.61

In [78]:
# sec 06
df = pd.read_csv('type1_data1.csv')
sub_df = df[(df['f3']=='gold')&(df['f2']==2)]
var_f1 = sub_df['f1'].var()
print(f"f1의 분산 : {var_f1:.2f}")

f1의 분산 : 235.43

In [83]:
# sec 07
df = pd.read_csv('type1_data1.csv')
df['age'] = df['age'] + 1
df_20s = df[(df['age']>=20) & (df['age'] < 30)]
df_30s = df[(df['age']>=30) & (df['age'] < 40)]
views_20s = df_20s['views'].mean()
views_30s = df_30s['views'].mean()
diff = round(abs(views_20s-views_30s),2)
diff

263.13

In [90]:
# sec 08
df = pd.read_csv('type1_data1.csv')
df['subscribed'] = pd.to_datetime(df['subscribed'])
df_2402 = df[(df['subscribed'].dt.year==2024)&(df['subscribed'].dt.month==2)]
print(len(df_2402[df_2402['f3']=='gold']))

5

In [100]:
# sec 09
df = pd.read_csv('type1_data1.csv')
df = df.dropna(subset='views')
df = df[df['views']<=1000]
df['f4'].mode()[0]

'ISFJ'

In [120]:
# sec 10
df = pd.read_csv('type1_data1.csv')
df = df.dropna()
df_city = df.groupby(by='city').mean(numeric_only=True)
df_city.sort_values(by='f2', ascending=False).index[0]

'서울'

In [124]:
# sec 11
df = pd.read_csv('type1_data1.csv')
df = df.dropna()
split = int(len(df)*0.7)
df = df[:split]
Q3 = df['views'].quantile(0.75)
Q1 = df['views'].quantile(0.25)
print(int(Q3-Q1))

2771

In [142]:
# sec 12
df = pd.read_csv('type1_data1.csv')
col1 = df.isna().sum().sort_values(ascending=False).index[0]
col2 = df.isna().sum().sort_values(ascending=False).index[1]
print(col1, col2)
df = df.dropna(subset=[col1])
mode_2 = df[col2].mode()[0]
print(mode_2)
# df[col2][df[col2].isna()] = mode_2
df[col2] = df[col2].fillna(mode_2)
print(int((df['f3']=='gold').sum()))

f1 f3
gold
63

In [153]:
# sec 13
df = pd.read_csv('type1_data1.csv')
df_na = df[df['f1'].isna()]
print(round(df_na['age'].mean(),2))

53.6

In [165]:
# sec 14
import numpy as np
df = pd.read_csv('type1_data1.csv')
df = df.drop_duplicates()
df['f3'] = df['f3'].replace({np.nan:0, 'silver':1, 'gold':2, 'vip':3})
print(int(df['f3'].sum()))

167

In [180]:
# sec 15
df = pd.read_csv('type1_data1.csv')
df = df.select_dtypes(exclude='object')
df = df.fillna(0)
(df.sum(axis=1) > 3000).sum()

88

In [187]:
# sec 16
df = pd.read_csv('type1_data1.csv')
Q1 = df['views'].quantile(0.25)
Q3 = df['views'].quantile(0.75)
IQR = Q3 - Q1
normal_condition = (df['views'] > Q1 - 1.5*IQR) & (df['views'] < Q3 + 1.5*IQR)
normal_df = df[normal_condition]
abnormal_df = df[~normal_condition]
print(int(abnormal_df['views'].sum()))

77699

In [192]:
# sec 17
df = pd.read_csv('type1_data1.csv')
std1 = df['views'].std()
cond1 = df['age'].round() == df['age']
cond2 = df['age'] > 0
df = df[cond1&cond2]
std2 = df['views'].std()
print(round(std1+std2,2))

8297.31

In [ ]:
# sec 18
df = pd.read_csv('type1_data2.csv', index_col='year')
print((df.loc[2001] > df.loc[2001].mean()).sum())
print((df.loc[2003] < df.loc[2003].mean()).sum())

100
102

In [256]:
# sec 19
df = pd.read_csv('type1_data1.csv')
df = df.bfill()
df2 = df.groupby(['city', 'f2']).sum(numeric_only=True).reset_index()
df2.sort_values(by='views', ascending=False).iloc[2]['city']
# df.sort_values(by='views', ascending=False).iloc[2]

'경기'

In [268]:
# sec 20
df = pd.read_csv('type1_data1.csv')
df['subscribed'] = pd.to_datetime(df['subscribed'])
df['월'] = df['subscribed'].dt.month
dfg = df.groupby(by=['월']).sum(numeric_only=True).reset_index()
print(int(dfg.sort_values(by=['views']).iloc[0]['월']))

11

In [271]:
# sec 21
df = pd.read_csv('delivery_time.csv')
df_late = df[df['실제도착시간'] > df['예상도착시간']]
print(len(df_late[df_late['거리']>=7]))

311

In [301]:
# sec 22
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
df['걸린시간(분)'] = (df['실제도착시간']-df['주문시간']).dt.total_seconds()/60
dfg = df.groupby(by=['앱종류']).mean(numeric_only=True).reset_index()
dfg = dfg.sort_values(by=['걸린시간(분)'])
print(f"가장 빠른 앱 : {dfg.iloc[0]['앱종류']}")
print(f"해당 앱의 평균도착시간 : {dfg.iloc[0]['걸린시간(분)']:.0f}")

가장 빠른 앱 : 배고팡
해당 앱의 평균도착시간 : 62

In [ ]:
# sec 23
df = pd.read_csv('delivery_time.csv')
df['늦음'] = df['실제도착시간'] > df['예상도착시간']
dfg = df.groupby(by='결제종류').mean(numeric_only=True).reset_index()
dfg = dfg.sort_values(by='늦음', ascending=False)
round(dfg.iloc[0]['늦음'],2)

0.56

In [319]:
df = pd.read_csv('delivery_time.csv')
df['늦음'] = df['실제도착시간'] > df['예상도착시간']
dfg = df.groupby('결제종류')['늦음'].mean()
round(dfg.max(),2)

0.56

In [339]:
# sec 24
df = pd.read_csv('delivery_time.csv')
dfg = df.groupby(by='user')['거리'].sum()
dfg = dfg.sort_values(ascending=False)
loyal_users = dfg[dfg>=50].index
df = df[df.user.isin(loyal_users)]
df['결제종류'].value_counts().sort_values(ascending=False).iloc[0]

48

In [382]:
# sec 25
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
users = df['user'].unique()
user2avgt = {}
for user in users:
    dfu = df[df.user==user].sort_values(by=['주문시간'])
    time_max = dfu['주문시간'].max()
    time_min = dfu['주문시간'].min()
    diff = (time_max - time_min).days
    if diff != 0:
        user2avgt[user] = diff
avgt = np.mean(list(user2avgt.values()))
users_over_avg = [user for user in user2avgt.keys() if user2avgt[user] > avgt]
print(len(users_over_avg))

146

In [419]:
# sec 26
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
df['주문연월'] = df['주문시간'].dt.strftime("%Y-%m")
max_ym = df['주문연월'].value_counts().index[0]
df = df[(df['주문연월']==max_ym)&(df['앱종류']=='배고팡')]
print(round((df['결제종류']=='앱결제').sum()/len(df),2))

0.31

In [434]:
# sec 27
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['주문시'] = df['주문시간'].dt.strftime('%H').astype(int)
df = df[df['주문시'].isin([10, 11, 12])]
df['걸린시간'] = (df['실제도착시간'] - df['주문시간']).dt.total_seconds()/60/60
df['평균속력'] = df['거리'] / df['걸린시간']
df['과속여부'] = df['평균속력'] >=50
print(df['과속여부'].sum())

1

In [444]:
# sec 28
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
df['주문연월'] = df['주문시간'].dt.strftime("%Y%m")
max_ym = df['주문연월'].value_counts().index[0]
print(max_ym)

202209

In [458]:
# sec 29
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
def fee(dist):
    if dist < 5:
        return 2000
    elif dist < 10:
        return 4000
    elif dist < 15:
        return 6000
    elif dist < 20:
        return 8000
df['배달료'] = df['거리'].apply(fee)
df['주문연도'] = df['주문시간'].dt.year
df['주문월'] = df['주문시간'].dt.month
dfg = df.groupby(by=['주문연도', '주문월'])['배달료'].sum().reset_index()
dfg = dfg.sort_values(by=['배달료'], ascending=False)
print(int(dfg.iloc[0]['배달료']))

448000

In [472]:
# sec 30
# 1. 주말 주문 건수와 평일 주문 건수를 구하시오
# 2. 주말 주문 건수와 평일 주문 건수의 차이를 절대값으로 구하고 정수형으로 구하시오.
df = pd.read_csv('delivery_time.csv')
df['주문시간'] = pd.to_datetime(df['주문시간'])
def is_weekend(DT):
    dow = DT.day_of_week
    if dow in [5,6]:
        return True
    elif dow in [0,1,2,3,4]:
        return False
df['주말'] = df['주문시간'].apply(is_weekend)
num_weekend = df['주말'].sum()
num_weekday = (~df['주말']).sum()
print(int(abs(num_weekend - num_weekday)))

412

In [477]:
# sec 31
# 1. 'user' 컬럼에서 user 뒤에 있는 숫자 값만 추출하시오
# 2. 추출된 숫자 값을 모두 합한 값을 정수로 구하시오.
df = pd.read_csv('delivery_time.csv')
df['num'] = df['user'].str[5:].astype(int)
print(df['num'].sum())

261387

In [480]:
# sec 32
# 1. 수학, 영어, 국어 점수의 합을 구하시오.
# 2. 합이 가장 큰 상위 10명을 찾으시오
# 3. 찾은 10명의 수학 평균점수를 구하시오 (반올림 후 정수 출력)
df = pd.read_csv('school_data.csv')
df['총점'] = df['수학'] + df['영어'] + df['국어']
df = df.sort_values(by=['총점'], ascending=False)
df_10 = df.iloc[:10]
print(df_10['이름'].to_list())
print(round(df_10['수학'].mean()))

['원숭이', '호랑이', '코끼리', '하이에나', '고양이', '독수리', '돌고래', '강치', '참새', '기린']
82

In [491]:
# sec 33
# 1. 과목에 상관없이 가장 작은 점수 25개를 찾으시오.
# 2. 찾은 점수 25개의 합을 정수로 구하시오
df = pd.read_csv('school_data.csv')
scores = df[['수학', '영어', '국어']].values.flatten()
bot_25 = np.sort(scores)[:25]
print(bot_25.sum())

420

In [494]:
df = pd.read_csv('school_data.csv')
long = df.melt(value_vars=['수학', '영어', '국어'],
               var_name='과목', value_name='점수')
long['점수'].nsmallest(25).sum()

420

In [510]:
# sec 34
# 1. 주어진 두 csv 파일을 학생 순서를 기준으로 병합하시오.
# 2. 학생별로 수학, 영어, 국어, 과학 점수의 평균을 구하시오.
# 3. 평균점수가 60점 이상인 인원 수를 계산하시오
df = pd.read_csv('school_data.csv')
df_science = pd.read_csv('school_data_science.csv')
print(df['이름'].to_list() == df_science['이름'].to_list())
df = pd.merge(df, df_science, on='이름')
df['평균'] = (df['수학'] + df['영어'] + df['국어'] + df['과학']) / 4
print(len(df[df['평균']>=60]))

True
9

In [513]:
df = pd.read_csv('school_data.csv')
df_science = pd.read_csv('school_data_science.csv')
df = pd.concat([df, df_science],axis=1)
df['평균'] = (df['수학'] + df['영어'] + df['국어'] + df['과학']) / 4
print(len(df[df['평균']>=60]))

9

In [ ]:
# sec 35
# 1. 주어진 두 csv 파일을 '이름'을 기준으로 합치시오
# 2. 영어교사가 장선생이면서 사회교사가 오선생인 학생들을 필터링하시오.
# 3. 필터링된 학생들의 수학 점수를 모두 더한 후 정수로 구하시오.
df = pd.read_csv('school_data.csv')
df_social = pd.read_csv('school_data_social.csv')
print(set(df['이름']) == set(df_social['이름'])) # True
print(len(df['이름']) == len(df_social['이름'])) # True
df = pd.merge(df, df_social, on=['이름'])
df = df[(df.영어교사=='장선생')&(df.사회교사=='오선생')]
print(int(df['수학'].sum()))

True
True
602

In [546]:
# sec 36
# 1. 결측된 판매금액은 해당 지역의 평균 판매금액으로 결측값을 대체하시오.
# 2. 각 거래마다 판매금액과 해당 지역의 평균 판매금액의 차이를 절댓값으로 구하시오.
# 3. 각 지역에서 차이값의 평균을 구한 후, 이 값이 가장 큰 지역의 지역코드를 구하시오.
df = pd.read_csv('sales.csv')
code2avg = dict(df.groupby('지역코드')['판매금액'].mean())
# print(code2avg)
for i, row in df.iterrows():
    sale = row['판매금액']
    code = row['지역코드']
    if pd.isna(sale):
        df.loc[i, '판매금액'] = code2avg[code]
df['지역평균'] = df['지역코드'].map(code2avg)
df['차이'] = abs(df['지역평균'] - df['판매금액'])
dfg = df.groupby(by='지역코드')['차이'].mean()
print(dfg.sort_values(ascending=False).index[0])

103

In [552]:
df = pd.read_csv('sales.csv')
code2avg = dict(df.groupby('지역코드')['판매금액'].mean())
df['판매금액'] = df['판매금액'].fillna(df['지역코드'].map(code2avg))
df['지역평균'] = df['지역코드'].map(code2avg)
df['차이'] = abs(df['지역평균'] - df['판매금액'])
dfg = df.groupby(by='지역코드')['차이'].mean()
print(dfg.sort_values(ascending=False).index[0])

103

In [ ]:
# sec 37
# 1. 각 행에서 판매수량과 단가를 이용하여 매출액을 계산하시오.
# 2. 요일을 평일과 주말로 구분하고, 매장별 평일과 주말 매출액 합계를 구하시오.
# 3. 매장별 평일과 주말 매출액 차이를 절대값으로 구하시오. 이후, 모든 매장 중 가장 큰 절댓값 차이를 찾으시오..
df = pd.read_csv('store_sales.csv')
df['매출'] = df['판매수량'] * df['단가']
weekend = ['토', '일']
df['주말'] = df['요일'].isin(weekend)
dfg = df.groupby(by=['매장코드','주말'])['매출'].sum().reset_index()
code2diff = dict()
for code in dfg.매장코드.unique():
    temp = dfg[dfg.매장코드==code]
    diff = temp.iloc[0]['매출'] - temp.iloc[1]['매출']
    code2diff[code] = abs(diff)
print(max(code2diff.values()))

241975

In [593]:
# sec 38
# 1. 각 region과 channel 조합별로 제품 A, B의 총 판매액을 계산하시오
# 2. 제품 A의 매출비율을 구하시오.
# 3. A 비율 중 최댓값을 찾아 반올림하여 소수 둘째자리까지 구하시오.
df = pd.read_csv('region_sales.csv')
# dfg = df.groupby(by=['Region', 'Channel', 'Product'])['Sales'].sum()
pdf = pd.pivot_table(df, index=['Region', 'Channel'], columns='Product', values='Sales', aggfunc='sum')
pdf['total'] = pdf['A'] + pdf['B']
pdf['A_ratio'] = pdf['A'] / pdf['total'] 
print(round(pdf['A_ratio'].max(),2))

0.51

In [ ]:
# sec 39
# 1. 지역과 월별 매출 합계를 구하시오.
# 2. 매출 합곅가 1400을 초과하는 경우가 몇 건인지 구하시오.
df = pd.read_csv('monthly_sales.csv')
# display(df)
mdf = pd.melt(
    df,
    id_vars='Region',
    value_vars = ['Jan', 'Feb', 'Mar'],
    var_name = 'Month',
    value_name = 'Sales'
)
mdfg = mdf.groupby(['Region', 'Month'])['Sales'].sum().reset_index()
print((mdfg['Sales'] >1400).sum())

6

: