In [1]:
import pandas as pd
train = pd.read_csv('train.csv')
test  = pd.read_csv('test.csv')
print(train.shape)
print(test.shape)

(29304, 16)
(3257, 15)

In [2]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29304 entries, 0 to 29303
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              29304 non-null  int64
 1   age             29292 non-null  float64
 2   workclass       27642 non-null  object
 3   fnlwgt          29304 non-null  int64
 4   education       29304 non-null  object
 5   education.num   29304 non-null  int64
 6   marital.status  29304 non-null  object
 7   occupation      27636 non-null  object
 8   relationship    29304 non-null  object
 9   race            29304 non-null  object
 10  sex             29304 non-null  object
 11  capital.gain    29304 non-null  int64
 12  capital.loss    29304 non-null  int64
 13  hours.per.week  29291 non-null  float64
 14  native.country  28767 non-null  object
 15  income          29304 non-null  object
dtypes: float64(2), int64(5), object(9)
memory usage: 3.6+ MB

In [3]:
train.describe()

,id,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,29304.000000,29292.000000,2.930400e+04,29304.000000,29304.000000,29304.000000,29291.000000
mean,16264.027880,38.553223,1.897488e+05,10.080842,1093.858722,86.744506,40.434229
std,9384.518323,13.628811,1.055250e+05,2.570824,7477.435640,401.518928,12.324036
min,0.000000,-38.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,8145.750000,28.000000,1.177890e+05,9.000000,0.000000,0.000000,40.000000
50%,16253.500000,37.000000,1.783765e+05,10.000000,0.000000,0.000000,40.000000
75%,24374.250000,48.000000,2.370682e+05,12.000000,0.000000,0.000000,45.000000
max,32560.000000,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [4]:
train.describe(include='object')

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
count,27642,29304,29304,27636,29304,29304,29304,28767,29304
unique,8,16,7,14,6,5,2,41,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,20451,9449,13466,3683,11845,25022,19578,26240,22263

In [5]:
train.isnull().sum()

id                   0
age                 12
workclass         1662
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1668
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week      13
native.country     537
income               0
dtype: int64

In [6]:
test.isnull().sum()

id                  0
age                 6
workclass         174
fnlwgt              0
education           0
education.num       0
marital.status      0
occupation        175
relationship        0
race                0
sex                 0
capital.gain        0
capital.loss        0
hours.per.week      9
native.country     46
dtype: int64

In [7]:
train['income'].value_counts()

income
<=50K    22263
>50K      7041
Name: count, dtype: int64

In [8]:
print(f"처리전 : {train.shape}")
df = train.dropna()
print(f"처리후 : {df.shape}")

처리전 : (29304, 16)
처리후 : (27096, 16)

In [9]:
df = train.dropna(subset=['native.country','workclass'])
df.isnull().sum()

id                 0
age               12
workclass          0
fnlwgt             0
education          0
education.num      0
marital.status     0
occupation         6
relationship       0
race               0
sex                0
capital.gain       0
capital.loss       0
hours.per.week    13
native.country     0
income             0
dtype: int64

In [10]:
print(f"처리전 : {train.shape}")
df = train.dropna(axis=1)
print(f"처리후 : {df.shape}")

처리전 : (29304, 16)
처리후 : (29304, 11)

In [11]:
print(f"처리전 : {train.shape}")
df = train.drop(columns=['native.country','workclass'])
print(f"처리후 : {df.shape}")

처리전 : (29304, 16)
처리후 : (29304, 14)

In [12]:
m = train['workclass'].mode()[0]
train['workclass'] = train['workclass'].fillna(m)
m = train['native.country'].mode()[0]
train['native.country'] = train['native.country'].fillna(m)
train.isnull().sum()

id                   0
age                 12
workclass            0
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1668
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week      13
native.country       0
income               0
dtype: int64

In [13]:
train['occupation'] = train['occupation'].fillna('X')
train['occupation'].isnull().sum()

0

In [14]:
test['workclass'] = test['workclass'].fillna(train['workclass'].mode()[0])
test['native.country'] = test['native.country'].fillna(train['native.country'].mode()[0])
test['occupation'] = test['occupation'].fillna(train['occupation'].mode()[0])
display(test.isnull().sum())

id                0
age               6
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    9
native.country    0
dtype: int64

In [15]:
# 평균값으로 채우기
value = int(train['age'].mean())
print(f"평균값:{value}")
train['age'] = train['age'].fillna(value)
test['age'] = test['age'].fillna(value)

평균값:38

In [16]:
# 중앙값으로 채우기
value = int(train['hours.per.week'].mean())
print(f"중앙값:{value}")
train['hours.per.week'] = train['hours.per.week'].fillna(value)
test['hours.per.week'] = test['hours.per.week'].fillna(value)

중앙값:40

In [17]:
print(train.shape)
train = train[train['age'] >0]
print(train.shape)

(29304, 16)
(29301, 16)

In [18]:
y_train = train.pop('income')

In [19]:
train_oh = pd.get_dummies(train)
test_oh = pd.get_dummies(test)
print(train.shape, test.shape, train_oh.shape, test_oh.shape)
train_oh

(29301, 15) (3257, 15) (29301, 107) (3257, 102)

,id,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
0,3331,34.0,177331,10,4386,0,40.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,19749,58.0,290661,9,0,0,40.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,1157,48.0,125933,10,0,1669,38.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,693,58.0,100313,10,0,1902,40.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,12522,41.0,195661,10,0,0,54.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29299,15999,28.0,47168,6,0,0,40.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
29300,21604,44.0,231793,16,0,0,38.0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
29301,26839,41.0,201435,9,0,0,40.0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
29302,16681,43.0,137722,9,0,0,40.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
29303,16069,22.0,406978,13,0,0,40.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [20]:
# cols = train.select_dtypes(include='object')
cols = train.columns[train.dtypes=='object']
cols

Index(['workclass', 'education', 'marital.status', 'occupation',
       'relationship', 'race', 'sex', 'native.country'],
      dtype='object')

In [21]:
from sklearn.preprocessing import LabelEncoder
for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.fit_transform(test[col])

In [22]:
print(len(set(train.columns)))
print(len(cols))
ncols = set(train.columns) - set(cols)

15
8

In [23]:
def get_data():
    train_copy = train.copy()
    test_copy = test.copy()
    return train_copy, test_copy

In [24]:
cols = ['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss', 'hours.per.week']

In [25]:
train_copy, test_copy = get_data()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
display(train_copy[cols].head(2))
train_copy[cols] = scaler.fit_transform(train_copy[cols])
test_copy[cols] = scaler.transform(test_copy[cols])
display(train_copy[cols].head(2))

    age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0  34.0  177331             10          4386             0            40.0
1  58.0  290661              9             0             0            40.0

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
0,0.232877,0.112092,0.600000,0.04386,0.0,0.397959
1,0.561644,0.189060,0.533333,0.00000,0.0,0.397959

In [26]:
train_copy, test_copy = get_data()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
display(train_copy[cols].head(2))
train_copy[cols] = scaler.fit_transform(train_copy[cols])
test_copy[cols] = scaler.transform(test_copy[cols])
display(train_copy[cols].head(2))

    age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0  34.0  177331             10          4386             0            40.0
1  58.0  290661              9             0             0            40.0

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
0,-0.335121,-0.117705,-0.031462,0.440247,-0.216056,-0.035121
1,1.428590,0.956277,-0.420430,-0.146298,-0.216056,-0.035121

In [27]:
train_copy, test_copy = get_data()

from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
display(train_copy[cols].head(2))
train_copy[cols] = scaler.fit_transform(train_copy[cols])
test_copy[cols] = scaler.transform(test_copy[cols])
display(train_copy[cols].head(2))

    age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0  34.0  177331             10          4386             0            40.0
1  58.0  290661              9             0             0            40.0

    age    fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0 -0.15 -0.008711       0.000000        4386.0           0.0             0.0
1  1.05  0.941438      -0.333333           0.0           0.0             0.0

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, y_train, test_size=0.2, random_state=0)
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((23440, 15), (5861, 15), (23440,), (5861,))

In [29]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)
pred = rf.predict_proba(X_val)
print(rf.classes_)
pred[:10]

['<=50K' '>50K']

array([[1.  , 0.  ],
       [1.  , 0.  ],
       [0.9 , 0.1 ],
       [0.63, 0.37],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.98, 0.02],
       [0.94, 0.06],
       [0.12, 0.88],
       [0.88, 0.12]])

In [30]:
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print(f'roc_auc : {roc_auc}')

roc_auc : 0.9173016455843583

In [31]:
pred = rf.predict(X_val)
pred

array(['<=50K', '<=50K', '<=50K', ..., '<=50K', '<=50K', '<=50K'],
      dtype=object)

In [32]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_val, pred)
print(f"accuracy : {accuracy:.2f}")

accuracy : 0.87

In [33]:
from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, pos_label='>50K')
print(f'f1 score : {f1:.2f}')

f1 score : 0.69

In [46]:
import lightgbm as lgb
lgbmc = lgb.LGBMClassifier(random_state=0, verbose=-1)
lgbmc.fit(X_train,y_train)
pred = lgbmc.predict_proba(X_val)

roc_auc = roc_auc_score(y_val, pred[:,1])
print(f"roc_auc : {roc_auc:.2f}")

pred = lgbmc.predict(X_val)
accuracy = accuracy_score(y_val, pred)
print(f"accuracy : {accuracy:.2f}")

f1 = f1_score(y_val, pred, pos_label=">50K")
print(f"f1 score : {f1:.2f}")

roc_auc : 0.93
accuracy : 0.88
f1 score : 0.72

In [47]:
pred = lgbmc.predict_proba(test)
pred

array([[0.92704668, 0.07295332],
       [0.97783555, 0.02216445],
       [0.97262543, 0.02737457],
       ...,
       [0.94482959, 0.05517041],
       [0.98791574, 0.01208426],
       [0.96679664, 0.03320336]])

In [48]:
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv('result.csv')